### ISSUE TITLE
IJ Lockup with LuaAnalysis

### ISSUE THREAD

**Issue by dcorbin** [Benjamin-Dobell/IntelliJ-Luanalysis#15]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | IJ2020.2 (locally built)
 Luanalysis version | 1.1.0 (locally built)
 OS                        | macOS 10.15.6

What are the steps to reproduce this issue?
------------------------------------------------
I was eating a file

What happens?
-------------
IJ locks up.  I'm unable to type anything. I must forcibly kill the IJ process

What were you expecting to happen?
-----------------------------------------
Editing should not lock up :)

Any logs, error output, etc?
------------------------------
I took a threadDump, and this was the only interesting thread:
"OurIconsCalculating Pool" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on com.intellij.util.indexing.StorageGuard@22b5658c
	at java.base@11.0.6/java.lang.Object.wait(Native Method)
	at java.base@11.0.6/java.lang.Object.wait(Object.java:328)
	at com.intellij.util.indexing.StorageGuard.doWait(StorageGuard.java:63)
	at com.intellij.util.indexing.StorageGuard.enter(StorageGuard.java:53)
	at com.intellij.util.indexing.StorageBufferingHandler.runUpdate(StorageBufferingHandler.java:15)
	at com.intellij.util.indexing.FileBasedIndexImpl.runCleanupAction(FileBasedIndexImpl.java:1005)
	at com.intellij.psi.stubs.StubIndexImpl.wipeProblematicFileIdsForParticularKeyAndStubIndex(StubIndexImpl.java:451)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:433)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:107)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:95)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex.get(LuaClassMemberIndex.kt:37)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processKey(LuaClassMemberIndex.kt:45)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processClassKey(LuaClassMemberIndex.kt:52)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processMember(LuaClassMemberIndex.kt:89)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processMember$default(LuaClassMemberIndex.kt:88)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.multiResolve(LuaPsiResolveUtil.kt:115)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1$1.invoke(Expressions.kt:354)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1$1.invoke(Expressions.kt)
	at com.tang.intellij.lua.search.SearchContext.withRecursionGuard(SearchContext.kt:202)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1.compute(Expressions.kt:353)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1.compute(Expressions.kt)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard(utils.kt:23)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard$default(utils.kt:22)
	at com.tang.intellij.lua.ty.ExpressionsKt.infer(Expressions.kt:338)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExprInner(Expressions.kt:104)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:64)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:40)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.search.SearchContext.inferAndCache(SearchContext.kt:228)
	at com.tang.intellij.lua.search.SearchContext.access$inferAndCache(SearchContext.kt:35)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:63)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:37)
	at com.tang.intellij.lua.search.SearchContext$Companion.with(SearchContext.kt:75)
	at com.tang.intellij.lua.search.SearchContext$Companion.infer(SearchContext.kt:63)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:30)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$guessParentType$parentTy$1.compute(LuaPsiImplUtil.kt:148)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$guessParentType$parentTy$1.compute(LuaPsiImplUtil.kt)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard(utils.kt:23)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard$default(utils.kt:22)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt.guessParentType(LuaPsiImplUtil.kt:147)
	at com.tang.intellij.lua.psi.impl.LuaClassMethodDefImpl.guessParentType(LuaClassMethodDefImpl.java:65)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtil.findOwnerClassGenericDef(LuaPsiTreeUtil.java:106)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtil.findOwnerClassGenericDef(LuaPsiTreeUtil.java:142)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtil.findGenericDef(LuaPsiTreeUtil.java:259)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtil.findGenericDef(LuaPsiTreeUtil.java:273)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.resolveType(LuaDocPsiImplUtil.kt:59)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:325)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocGeneralTyImpl.getType(LuaDocGeneralTyImpl.java:38)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:165)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocTagReturnImpl.getType(LuaDocTagReturnImpl.java:51)
	at com.tang.intellij.lua.stubs.LuaClassMethodType.createStub(LuaClassMethodStub.kt:65)
	at com.tang.intellij.lua.stubs.LuaClassMethodType.createStub(LuaClassMethodStub.kt:34)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.createStub(DefaultStubBuilder.java:85)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:60)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:55)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:33)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:22)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:128)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.lambda$computeValue$0(StubUpdatingIndex.java:145)
	at com.intellij.psi.stubs.StubUpdatingIndex$1$$Lambda$2798/0x0000000801dae840.compute(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:126)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:99)
	at com.intellij.util.indexing.SingleEntryCompositeIndexer.computeValue(SingleEntryCompositeIndexer.java:27)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:28)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:17)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:317)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:150)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:40)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:267)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:239)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$indexUnsavedDocument$14(FileBasedIndexImpl.java:973)
	at com.intellij.util.indexing.FileBasedIndexImpl$$Lambda$4033/0x0000000802aa7840.run(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:722)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocument(FileBasedIndexImpl.java:942)
	at com.intellij.util.indexing.RegisteredIndexes$DocumentUpdateTask.doProcess(RegisteredIndexes.java:197)
	at com.intellij.util.indexing.RegisteredIndexes$DocumentUpdateTask.doProcess(RegisteredIndexes.java:188)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:77)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:46)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$indexUnsavedDocuments$13(FileBasedIndexImpl.java:901)
	at com.intellij.util.indexing.FileBasedIndexImpl$$Lambda$4027/0x0000000802aa5040.compute(Unknown Source)
	at com.intellij.util.indexing.StorageBufferingHandler.runUpdate(StorageBufferingHandler.java:30)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocuments(FileBasedIndexImpl.java:901)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:689)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:540)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:396)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:107)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:95)
	at org.jetbrains.kotlin.idea.stubindex.KotlinFileFacadeFqNameIndex.get(KotlinFileFacadeFqNameIndex.kt:19)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport$findFilesForFacade$1.invoke(IDEKotlinAsJavaSupport.kt:243)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport$findFilesForFacade$1.invoke(IDEKotlinAsJavaSupport.kt:40)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt$sam$com_intellij_openapi_util_Computable$0.compute(ApplicationUtils.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:880)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runReadAction(ApplicationUtils.kt:28)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport.findFilesForFacade(IDEKotlinAsJavaSupport.kt:242)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport.getFacadeClasses(IDEKotlinAsJavaSupport.kt:171)
	at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClasses(JavaElementFinder.kt:58)
	at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClass(JavaElementFinder.kt:46)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:107)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:84)
	at com.intellij.micronaut.MicronautUtils.hasMicronautLibrary(MicronautUtils.kt:62)
	at com.intellij.micronaut.config.MnIconProvider.getIcon(MnIconProvider.kt:13)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:199)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:143)
	at com.intellij.util.IconUtil$$Lambda$886/0x0000000800b6f440.fun(Unknown Source)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:268)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:158)
	at com.intellij.ui.DeferredIconImpl$$Lambda$863/0x0000000800afb840.run(Unknown Source)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:98)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:158)
	at com.intellij.ui.DeferredIconImpl$$Lambda$860/0x0000000800afe040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$861/0x0000000800afc840.run(Unknown Source)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$862/0x0000000800afc040.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$406/0x0000000800511040.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:96)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:157)
	at com.intellij.ui.DeferredIconImpl$$Lambda$858/0x0000000800affc40.run(Unknown Source)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1$$Lambda$431/0x000000080058f040.run(Unknown Source)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)

**Comment by Benjamin-Dobell** [comment]
I believe this is resolved on master. If not, please let me know.
