### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Muhammad-Ali-611** [Benjamin-Dobell/IntelliJ-Luanalysis#155]
## Environment

Name | Version
-----|--------
IDEA version | [e.g. IC2018.2 EAP, CL2018.1.2]
Luanalysis version | [e.g. v1.2.5]
OS | [e.g. macOS 10.13.4, Windows 10]
 
 
## Preferences

(Preferences -> Languages & Frameworks > Luanalysis)

### Lua

Name | Setting  
-----|--------
Language level | [e.g. Lua 5.3]

### Type Safety

Name | Setting
-----|--------
Strict nil checks | ☑️ / ❎
Unknown type (any) is indexable | ☑️ / ❎
Unknown type (any) is callabale | ☑️ / ❎

## What are the steps to reproduce this issue?

1. …
2. …
3. …

## What happens?

…

## What were you expecting to happen?

…

## Any logs, error output, etc?

…

## Any other comments?

…

**Comment by Muhammad-Ali-611** [comment]
com.intellij.diagnostic.PluginException: Key com.tang.intellij.lua.project.LuaSettings duplicated; existingAdapter: ServiceAdapter(descriptor=ServiceDescriptor(interface='null', serviceImplementation='com.tang.intellij.lua.project.LuaSettings', testServiceImplementation='null', headlessImplementation='null', overrides=false, configurationSchemaKey='null', preload=FALSE, client=null), pluginDescriptor=PluginDescriptor(name=EmmyLua, id=com.tang, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.1/plugins/EmmyLua, version=1.3.20-IDEA231, package=null, isBundled=false)); descriptor: com.tang.intellij.lua.project.LuaSettings; app: Application (containerState PRE_INIT) ; current plugin: au.com.glassechidna.luanalysis
at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:588)
at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:293)
at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:46)
at com.intellij.idea.ApplicationLoader.doInitApplication(ApplicationLoader.kt:86)
at com.intellij.idea.ApplicationLoader.access$doInitApplication(ApplicationLoader.kt:1)
at com.intellij.idea.ApplicationLoader$doInitApplication$1.invokeSuspend(ApplicationLoader.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.intellij.idea.Z.Z(Z.java:73)
at com.intellij.ide.S.s.r.Z(r.java:139)
at com.intellij.ide.S.s.Zu.Z(Zu.java:196)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.intellij.idea.MainImpl.start(MainImpl.kt:62)
at com.intellij.idea.StartupUtil$startApplication$7.invokeSuspend(StartupUtil.kt:297)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
at com.intellij.idea.Main.main(Main.kt:40)

-----
Your JRE: 17.0.6+10-b829.9 aarch64 (JetBrains s.r.o.)
/private/var/folders/9k/d1shf9sd69ddgpzrmrqz2kvc0000gn/T/AppTranslocation/FA54C50A-B19F-438C-A8E1-324685BD8773/d/IntelliJ IDEA.app/Contents/jbr/Contents/Home
