### ISSUE TITLE
Indexing field freezes the IDEA

### ISSUE THREAD

**Issue by PalaBeaveR** [Benjamin-Dobell/IntelliJ-Luanalysis#25]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | IC2020.3
 Luanalysis version | 1.1.0-IDEA201
 OS                        | Windows 10

What are the steps to reproduce this issue?
------------------------------------------------
1. Open Player.def.lua in tts-types/tts
2. Append this snippet of code to the end of the file
```
---@return string[]
function Player.getAvailableColors() end
```
3. Create a new field after line 51 like this one 
`---@field [string]`

What happens?
-------------
As soon as you type
`---@field [s`
IntelliJ IDEA freezes completely

Any logs, error output, etc?
------------------------------
```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:177)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:143)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:105)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:59)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:150)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:92)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:71)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:289)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:325)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:105)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:93)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex.get(LuaClassMemberIndex.kt:37)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processKey(LuaClassMemberIndex.kt:45)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processClassKey(LuaClassMemberIndex.kt:52)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processMember(LuaClassMemberIndex.kt:89)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processMember$default(LuaClassMemberIndex.kt:88)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.multiResolve(LuaPsiResolveUtil.kt:115)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1$1.invoke(Expressions.kt:354)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1$1.invoke(Expressions.kt)
	at com.tang.intellij.lua.search.SearchContext.withRecursionGuard(SearchContext.kt:202)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1.compute(Expressions.kt:353)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1.compute(Expressions.kt)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard(utils.kt:23)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard$default(utils.kt:22)
	at com.tang.intellij.lua.ty.ExpressionsKt.infer(Expressions.kt:338)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExprInner(Expressions.kt:104)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:64)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:40)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.search.SearchContext.inferAndCache(SearchContext.kt:228)
	at com.tang.intellij.lua.search.SearchContext.access$inferAndCache(SearchContext.kt:35)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:63)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:37)
	at com.tang.intellij.lua.search.SearchContext$Companion.with(SearchContext.kt:68)
	at com.tang.intellij.lua.search.SearchContext$Companion.infer(SearchContext.kt:63)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:30)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:59)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:40)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.search.SearchContext.inferAndCache(SearchContext.kt:228)
	at com.tang.intellij.lua.search.SearchContext.access$inferAndCache(SearchContext.kt:35)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:63)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:37)
	at com.tang.intellij.lua.search.SearchContext$Companion.with(SearchContext.kt:75)
	at com.tang.intellij.lua.search.SearchContext$Companion.infer(SearchContext.kt:63)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:30)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$guessParentType$parentTy$1.compute(LuaPsiImplUtil.kt:148)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$guessParentType$parentTy$1.compute(LuaPsiImplUtil.kt)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard(utils.kt:23)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard$default(utils.kt:22)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt.guessParentType(LuaPsiImplUtil.kt:147)
	at com.tang.intellij.lua.psi.impl.LuaClassMethodDefImpl.guessParentType(LuaClassMethodDefImpl.java:65)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtil.findOwnerClassGenericDef(LuaPsiTreeUtil.java:106)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtil.findOwnerClassGenericDef(LuaPsiTreeUtil.java:142)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtil.findGenericDef(LuaPsiTreeUtil.java:259)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtil.findGenericDef(LuaPsiTreeUtil.java:273)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.resolveType(LuaDocPsiImplUtil.kt:59)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:325)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocGeneralTyImpl.getType(LuaDocGeneralTyImpl.java:38)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:320)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocArrTyImpl.getType(LuaDocArrTyImpl.java:38)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:165)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocTagReturnImpl.getType(LuaDocTagReturnImpl.java:51)
	at com.tang.intellij.lua.stubs.LuaClassMethodType.createStub(LuaClassMethodStub.kt:65)
	at com.tang.intellij.lua.stubs.LuaClassMethodType.createStub(LuaClassMethodStub.kt:34)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.createStub(DefaultStubBuilder.java:85)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:60)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:55)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:33)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:22)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:122)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:172)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:150)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:117)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:30)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:19)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:291)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:283)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:168)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:46)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:226)
	at com.intellij.psi.stubs.StubUpdatingIndex$MyIndex.mapInputAndPrepareUpdate(StubUpdatingIndex.java:444)
	at com.intellij.psi.stubs.StubUpdatingIndex$MyIndex.mapInputAndPrepareUpdate(StubUpdatingIndex.java:408)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$indexUnsavedDocument$12(FileBasedIndexImpl.java:1023)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:555)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocument(FileBasedIndexImpl.java:995)
	at com.intellij.util.indexing.RegisteredIndexes$DocumentUpdateTask.doProcess(RegisteredIndexes.java:181)
	at com.intellij.util.indexing.RegisteredIndexes$DocumentUpdateTask.doProcess(RegisteredIndexes.java:172)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:64)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:33)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$indexUnsavedDocuments$11(FileBasedIndexImpl.java:951)
	at com.intellij.util.indexing.StorageBufferingHandler.runUpdate(StorageBufferingHandler.java:33)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocuments(FileBasedIndexImpl.java:951)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:726)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:463)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:296)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:49)
	at com.intellij.psi.stubs.StubIndex.get(StubIndex.java:39)
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java:22)
	at com.tang.intellij.lua.stubs.index.LuaClassIndex$Companion.process(LuaClassIndex.kt:60)
	at com.tang.intellij.lua.stubs.index.LuaClassIndex$Companion.find(LuaClassIndex.kt:52)
	at com.tang.intellij.lua.stubs.index.LuaClassIndex$Companion.find(LuaClassIndex.kt:47)
	at com.tang.intellij.lua.psi.search.LuaShortNamesManagerImpl.findClass(LuaShortNamesManagerImpl.kt:39)
	at com.tang.intellij.lua.psi.search.CompositeLuaShortNamesManager.findClass(CompositeLuaShortNamesManager.kt:42)
	at com.tang.intellij.lua.psi.search.LuaShortNamesManager.findType(LuaShortNamesManager.kt:70)
	at com.tang.intellij.lua.comment.reference.LuaClassNameReference.resolve(LuaClassNameReference.kt:49)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:177)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:165)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:204)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:248)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:227)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:295)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:175)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:136)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:43)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:24)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:233)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:225)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:85)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$updateHighlighted$1(BackgroundHighlighter.java:147)
	at com.intellij.codeInsight.highlighting.BackgroundHighlightingUtil.lambda$lookForInjectedFileInOtherThread$0(BackgroundHighlightingUtil.java:55)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Benjamin-Dobell** [comment]
Current Jetbrains release, not master?

**Comment by PalaBeaveR** [comment]
If you're talking about the plugin then the version number is from the plugins section in settings and downloaded from there too so I think current Jetbrains release?

**Comment by Benjamin-Dobell** [comment]
Not a worry. I believe this is already fixed. If you're able to follow the instructions in this repo to build the latest version and try it that'd be appreciated. Otherwise I plan to make a release in the next few days.

**Comment by PalaBeaveR** [comment]
Late response, but I can't replicate the error so I think that 1.2 fixed it.

**Comment by Benjamin-Dobell** [comment]
Great to hear. Thanks for letting me know.
