### ISSUE TITLE
Key duplicated on Windows

### ISSUE THREAD

**Issue by kerwanp** [Benjamin-Dobell/IntelliJ-Luanalysis#75]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | 2021.1.2  Build #IU-211.7442.40
 Luanalysis version | v1.2.3
 OS                        | Windows 10

What are the steps to reproduce this issue?
------------------------------------------------
1. Install Luanalysis
2. Restart the idea

What happens?
-------------
The idea does not start and show a critical error.

What were you expecting to happen?
-----------------------------------------
Having the IDEA starting properly.

Any logs, error output, etc?
------------------------------
```
2021-06-05 15:28:08,486 [   1288]   INFO -                         STDERR - Start Failed 
2021-06-05 15:28:08,486 [   1288]   INFO -                         STDERR - Internal error. Please refer to https://jb.gg/ide/critical-startup-errors 
2021-06-05 15:28:08,486 [   1288]   INFO -                         STDERR -  
2021-06-05 15:28:08,486 [   1288]   INFO -                         STDERR - java.util.concurrent.CompletionException: org.picocontainer.PicoRegistrationException: Key com.tang.intellij.lua.luacheck.LuaCheckSettings duplicated 
2021-06-05 15:28:08,486 [   1288]   INFO -                         STDERR - 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) 
2021-06-05 15:28:08,486 [   1288]   INFO -                         STDERR - 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.idea.ApplicationLoader.registerAppComponents(ApplicationLoader.kt:104) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.idea.ApplicationLoader.executeInitAppInEdt(ApplicationLoader.kt:63) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.idea.ApplicationLoader.access$executeInitAppInEdt(ApplicationLoader.kt:1) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.idea.ApplicationLoader$initApplication$1$1.run(ApplicationLoader.kt:363) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - Caused by: org.picocontainer.PicoRegistrationException: Key com.tang.intellij.lua.luacheck.LuaCheckSettings duplicated 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:119) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:400) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:250) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:106) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR - 	... 19 more 
2021-06-05 15:28:08,487 [   1289]   INFO -                         STDERR -  
2021-06-05 15:28:08,488 [   1290]   INFO -                         STDERR - ----- 
```

**Comment by kerwanp** [comment]
Getting the same problem on Debian GNU/Linux 10 (buster)

**Comment by Benjamin-Dobell** [comment]
@kerwanp I believe this occurs when you have both Luanalysis and EmmyLua installed simultaneously.

Luanalysis was forked from EmmyLua. The initial goal was to contribute everything upstream, so EmmyLua's settings (and storage there-of) were left unaltered. However, since then, Luanalysis' internals have diverged quite considerably from EmmyLua. At this pointit would be wise for me to go back through and stop making use of the `com.tang.intellij.lua` scope, which quite rightly belongs to EmmyLua.

For now, please ensure EmmyLua is not installed alongside Luanalysis.

**Comment by kerwanp** [comment]
That was the point, closing the issue.
