### ISSUE TITLE
Reporting Java null pointer exception

### ISSUE THREAD

**Issue by dbledet** [Benjamin-Dobell/IntelliJ-Luanalysis#94]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | CLion 2021.2
Build #CL-212.4746.93, built on July 27, 2021
Licensed to NETGEAR / David Ledet
Subscription is active until May 7, 2022.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-25-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 2
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: au.com.glassechidna.luanalysis (1.3.0), zielu.gittoolbox (212.6.6)
Current Desktop: ubuntu:GNOME

 Luanalysis version | v1.3.0
 OS                        | Linux ubuntu 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

What are the steps to reproduce this issue?
------------------------------------------------
No repo steps.  Just happen sometimes editing complicated lua files.

What happens?
-------------
java.lang.NullPointerException
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$getPresentation$2.getPresentableText(LuaPsiImplUtil.kt:180)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.update(PsiElement2UsageTargetAdapter.java:279)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:63)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:68)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:90)
	at com.intellij.find.findUsages.DefaultUsageTargetProvider.getTargets(DefaultUsageTargetProvider.java:17)
	at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:51)
	at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:32)
	at com.intellij.ide.impl.dataRules.UsageTargetsRule.getData(UsageTargetsRule.java:13)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRule$4(DataManagerImpl.java:116)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:73)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:126)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.ensureSlowDataKeysPreCached(ActionUpdater.java:344)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:273)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$16(ActionUpdater.java:298)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$17(ActionUpdater.java:295)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$18(ActionUpdater.java:294)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$19(ActionUpdater.java:292)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

What were you expecting to happen?
-----------------------------------------
…

Any logs, error output, etc?
------------------------------
…

Any other comments?
------------------------
…

**Comment by Arakade** [comment]
Hi. #147 suggests you thought this would be fixed in 1.4.1.  Is that available yet?
